In [ ]:
## import pandas
import pandas as pd

## open file
data1 = pd.read_csv("H255.csv")

# test
data1.head()

,DUID,PID,DUPERSID,CONDN,CONDIDX,PANEL,CONDRN,AGEDIAG,CRND1,CRND2,...,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND,PERWT24F,VARSTR,VARPSU
0,2810003,101,2810003101,1,2810003101001,28,1,65,-1,-1,...,-1,2,2,2,2,2,1,16532.1794,2062,1
1,2810003,101,2810003101,4,2810003101004,28,1,-1,-1,-1,...,-1,2,2,2,1,2,2,16532.1794,2062,1
2,2810003,101,2810003101,8,2810003101008,28,1,-1,-1,-1,...,-1,2,2,2,2,2,1,16532.1794,2062,1
3,2810003,101,2810003101,9,2810003101009,28,1,-1,-1,-1,...,-1,2,2,2,2,2,1,16532.1794,2062,1
4,2810003,101,2810003101,10,2810003101010,28,2,-1,-1,-1,...,-1,2,2,2,1,2,2,16532.1794,2062,1

In [ ]:
data1.describe

<bound method NDFrame.describe of           DUID  PID    DUPERSID  CONDN        CONDIDX  PANEL  CONDRN  AGEDIAG  \
0      2810003  101  2810003101      1  2810003101001     28       1       65
1      2810003  101  2810003101      4  2810003101004     28       1       -1
2      2810003  101  2810003101      8  2810003101008     28       1       -1
3      2810003  101  2810003101      9  2810003101009     28       1       -1
4      2810003  101  2810003101     10  2810003101010     28       2       -1
...        ...  ...         ...    ...            ...    ...     ...      ...
67700  2930421  102  2930421102      1  2930421102001     29       2       -1
67701  2930421  102  2930421102      2  2930421102002     29       3       -1
67702  2930421  102  2930421102      3  2930421102003     29       3       -1
67703  2930421  104  2930421104      1  2930421104001     29       2       -1
67704  2930421  104  2930421104      2  2930421104002     29       2       -1

       CRND1  CRND2  ...  CCSR4X  HHCOND  IPCOND  OPCOND  OBCOND ERCOND  \
0         -1     -1  ...      -1       2       2       2       2      2
1         -1     -1  ...      -1       2       2       2       1      2
2         -1     -1  ...      -1       2       2       2       2      2
3         -1     -1  ...      -1       2       2       2       2      2
4         -1     -1  ...      -1       2       2       2       1      2
...      ...    ...  ...     ...     ...     ...     ...     ...    ...
67700      0      1  ...      -1       2       2       2       1      2
67701      0      0  ...      -1       2       2       2       2      2
67702      0      0  ...      -1       2       2       2       2      2
67703      0      1  ...      -1       2       2       2       1      2
67704      0      1  ...      -1       2       2       2       1      2

      RXCOND     PERWT24F VARSTR VARPSU
0          1  16532.17940   2062      1
1          2  16532.17940   2062      1
2          1  16532.17940   2062      1
3          1  16532.17940   2062      1
4          2  16532.17940   2062      1
...      ...          ...    ...    ...
67700      1  17515.06225   2065      1
67701      1  17515.06225   2065      1
67702      1  17515.06225   2065      1
67703      2  15202.02402   2065      1
67704      2  15202.02402   2065      1

[67705 rows x 29 columns]>

In [3]:
data2= pd.read_csv('h256.csv')
data2.head(10)

,DUID,PID,DUPERSID,PANEL,DATAYEAR,FAMID31,FAMID42,FAMID53,FAMID24,FAMIDYR,...,RXOTH24,PERWT24F,FAMWT24F,FAMWT24C,VARSTR,VARPSU,SAQWT24F,CSAQW24F,ESAQWT24F,PESAQWT24F
0,2810003,101,2810003101,28,2024,A,A,A,A,A,...,0,16532.179400,14481.891790,14481.891790,2062,1,19220.259040,0.0,19419.845140,22951.575300
1,2810006,101,2810006101,28,2024,A,A,A,A,A,...,0,41818.011780,44596.922710,44596.922710,2012,1,56091.114790,0.0,53136.862860,55108.036890
2,2810006,102,2810006102,28,2024,A,A,A,A,A,...,0,31330.068630,44596.922710,44596.922710,2012,1,48905.537990,0.0,53953.868360,56373.565370
3,2810006,103,2810006103,28,2024,A,A,A,A,A,...,0,47067.704700,44596.922710,44596.922710,2012,1,0.000000,0.0,0.000000,0.000000
4,2810006,104,2810006104,28,2024,A,A,A,A,A,...,0,33240.146510,44596.922710,44596.922710,2012,1,64420.763840,0.0,86534.512830,77577.353500
5,2810007,101,2810007101,28,2024,A,A,A,A,A,...,0,5004.866703,7545.601087,7545.601087,2090,1,7567.013278,0.0,6336.149625,5446.232183
6,2810007,102,2810007102,28,2024,A,A,A,A,A,...,0,5831.762703,7545.601087,7545.601087,2090,1,0.000000,0.0,0.000000,0.000000
7,2810007,109,2810007109,28,2024,A,A,A,A,A,...,0,11214.384310,7545.601087,7545.601087,2090,1,29630.563750,0.0,16343.438460,28474.244540
8,2810009,101,2810009101,28,2024,A,A,A,A,A,...,0,9203.100031,11345.957560,11345.957560,2041,1,13062.384070,0.0,0.000000,0.000000
9,2810013,101,2810013101,28,2024,A,A,A,A,A,...,106,34347.016780,35988.922980,35988.922980,2018,5,0.000000,0.0,0.000000,0.000000

In [4]:
data = pd.merge(left = data2, right = data1 , how="inner", on='DUPERSID')
data

,DUID_x,PID_x,DUPERSID,PANEL_x,DATAYEAR,FAMID31,FAMID42,FAMID53,FAMID24,FAMIDYR,...,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND,PERWT24F_y,VARSTR_y,VARPSU_y
0,2810003,101,2810003101,28,2024,A,A,A,A,A,...,-1,2,2,2,2,2,1,16532.17940,2062,1
1,2810003,101,2810003101,28,2024,A,A,A,A,A,...,-1,2,2,2,1,2,2,16532.17940,2062,1
2,2810003,101,2810003101,28,2024,A,A,A,A,A,...,-1,2,2,2,2,2,1,16532.17940,2062,1
3,2810003,101,2810003101,28,2024,A,A,A,A,A,...,-1,2,2,2,2,2,1,16532.17940,2062,1
4,2810003,101,2810003101,28,2024,A,A,A,A,A,...,-1,2,2,2,1,2,2,16532.17940,2062,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67700,2930421,102,2930421102,29,2024,A,A,A,A,A,...,-1,2,2,2,1,2,1,17515.06225,2065,1
67701,2930421,102,2930421102,29,2024,A,A,A,A,A,...,-1,2,2,2,2,2,1,17515.06225,2065,1
67702,2930421,102,2930421102,29,2024,A,A,A,A,A,...,-1,2,2,2,2,2,1,17515.06225,2065,1
67703,2930421,104,2930421104,29,2024,A,A,A,A,A,...,-1,2,2,2,1,2,2,15202.02402,2065,1
67704,2930421,104,2930421104,29,2024,A,A,A,A,A,...,-1,2,2,2,1,2,2,15202.02402,2065,1

In [5]:
data.columns

Index(['DUID_x', 'PID_x', 'DUPERSID', 'PANEL_x', 'DATAYEAR', 'FAMID31',
       'FAMID42', 'FAMID53', 'FAMID24', 'FAMIDYR',
       ...
       'CCSR4X', 'HHCOND', 'IPCOND', 'OPCOND', 'OBCOND', 'ERCOND', 'RXCOND',
       'PERWT24F_y', 'VARSTR_y', 'VARPSU_y'],
      dtype='object', length=1643)

In [6]:
## See how to use for loop

for column in data.columns:
    if "_x" in column:
        # change column names
        data.rename(columns={column: column.replace("_x", "")}, inplace=True)
    elif "_y" in column:
        # drop unnecessary columns column 
        data = data.drop([column], axis=1)

In [7]:
data.columns

Index(['DUID', 'PID', 'DUPERSID', 'PANEL', 'DATAYEAR', 'FAMID31', 'FAMID42',
       'FAMID53', 'FAMID24', 'FAMIDYR',
       ...
       'CCSR1X', 'CCSR2X', 'CCSR3X', 'CCSR4X', 'HHCOND', 'IPCOND', 'OPCOND',
       'OBCOND', 'ERCOND', 'RXCOND'],
      dtype='object', length=1637)

In [8]:
data

,DUID,PID,DUPERSID,PANEL,DATAYEAR,FAMID31,FAMID42,FAMID53,FAMID24,FAMIDYR,...,CCSR1X,CCSR2X,CCSR3X,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND
0,2810003,101,2810003101,28,2024,A,A,A,A,A,...,END010,-1,-1,-1,2,2,2,2,2,1
1,2810003,101,2810003101,28,2024,A,A,A,A,A,...,MUS009,-1,-1,-1,2,2,2,1,2,2
2,2810003,101,2810003101,28,2024,A,A,A,A,A,...,NVS006,NVS016,-1,-1,2,2,2,2,2,1
3,2810003,101,2810003101,28,2024,A,A,A,A,A,...,NVS016,-1,-1,-1,2,2,2,2,2,1
4,2810003,101,2810003101,28,2024,A,A,A,A,A,...,MUS011,-1,-1,-1,2,2,2,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67700,2930421,102,2930421102,29,2024,A,A,A,A,A,...,NVS010,SYM010,-1,-1,2,2,2,1,2,1
67701,2930421,102,2930421102,29,2024,A,A,A,A,A,...,SYM018,-1,-1,-1,2,2,2,2,2,1
67702,2930421,102,2930421102,29,2024,A,A,A,A,A,...,END010,-1,-1,-1,2,2,2,2,2,1
67703,2930421,104,2930421104,29,2024,A,A,A,A,A,...,EYE000,-1,-1,-1,2,2,2,1,2,2
67704,2930421,104,2930421104,29,2024,A,A,A,A,A,...,EYE009,-1,-1,-1,2,2,2,1,2,2

In [9]:
# See what F41-ish values actually exist in your data
data['ICD10CDX'].astype(str)[data['ICD10CDX'].astype(str).str.startswith('F41')].unique()

array(['F41'], dtype=object)

In [10]:
data_f41 = data[data['ICD10CDX'] == 'F41'].copy()
data_f41.shape[0]

1957

In [11]:
data_f41.describe

<bound method NDFrame.describe of           DUID  PID    DUPERSID  PANEL  DATAYEAR FAMID31 FAMID42 FAMID53  \
7      2810003  101  2810003101     28      2024       A       A       A
26     2810013  101  2810013101     28      2024       A       A       A
121    2810035  101  2810035101     28      2024       A       A       A
139    2810045  102  2810045102     28      2024       B       B       B
155    2810048  101  2810048101     28      2024       B       B       B
...        ...  ...         ...    ...       ...     ...     ...     ...
67566  2930389  101  2930389101     29      2024       A       A       A
67586  2930389  102  2930389102     29      2024       A       A       A
67631  2930398  101  2930398101     29      2024       A       A       A
67636  2930398  102  2930398102     29      2024       A       A       A
67653  2930408  101  2930408101     29      2024       A       A       A

      FAMID24 FAMIDYR  ...  CCSR1X  CCSR2X  CCSR3X CCSR4X HHCOND IPCOND  \
7           A       A  ...  MBD005      -1      -1     -1      2      2
26          A       A  ...  MBD005      -1      -1     -1      2      2
121         A       A  ...  MBD005      -1      -1     -1      2      2
139         B       B  ...  MBD005      -1      -1     -1      2      2
155         B       B  ...  MBD005      -1      -1     -1      2      2
...       ...     ...  ...     ...     ...     ...    ...    ...    ...
67566       A       A  ...  MBD005      -1      -1     -1      2      2
67586       A       A  ...  MBD005      -1      -1     -1      2      2
67631       A       A  ...  MBD005      -1      -1     -1      2      2
67636       A       A  ...  MBD005      -1      -1     -1      2      2
67653       A       A  ...  MBD005      -1      -1     -1      2      2

      OPCOND  OBCOND  ERCOND  RXCOND
7          2       1       2       1
26         2       2       2       1
121        2       2       2       1
139        2       2       2       1
155        2       2       2       1
...      ...     ...     ...     ...
67566      2       1       2       1
67586      2       1       2       1
67631      2       2       2       1
67636      2       1       2       2
67653      1       2       2       1

[1957 rows x 1637 columns]>

In [12]:
data_f41['DUPERSID'].duplicated().sum()

np.int64(58)

In [13]:
data_f41.drop_duplicates(subset=['DUPERSID'], keep= 'first', inplace = True)

In [14]:
data_f41['DUPERSID'].duplicated().sum()

np.int64(0)

In [16]:
data_f41.to_csv('F41_cleaned.csv', index=False)